import type { GlossaryEntry } from "@/types/course";

export const glossary: GlossaryEntry[] = [
  // Fundamentos Cloud
  { en: "Cloud Computing", es: "Entrega de servicios IT (compute, storage, BD, red, software) por internet, on-demand y con pago por uso", cat: "Fundamentos" },
  { en: "IaaS", es: "Infrastructure as a Service: el proveedor da VMs, red, storage; tú gestionas OS y arriba (ej. Compute Engine)", cat: "Fundamentos" },
  { en: "PaaS", es: "Platform as a Service: el proveedor gestiona OS y runtime, tú solo despliegas tu app (ej. App Engine)", cat: "Fundamentos" },
  { en: "SaaS", es: "Software as a Service: el software listo para usar vía web (ej. Gmail, Workspace)", cat: "Fundamentos" },
  { en: "CapEx", es: "Capital Expenditure: gasto en activos (servidores físicos). Cloud lo reduce drásticamente.", cat: "Fundamentos" },
  { en: "OpEx", es: "Operating Expenditure: gasto operativo recurrente. El cloud convierte CapEx en OpEx.", cat: "Fundamentos" },
  { en: "TCO", es: "Total Cost of Ownership: costo total de poseer y operar un activo", cat: "Fundamentos" },
  { en: "Shared Responsibility Model", es: "Modelo donde Google y el cliente se reparten responsabilidades de seguridad", cat: "Fundamentos" },
  // Compute
  { en: "Compute Engine", es: "VMs (IaaS) en Google Cloud. Máquinas virtuales personalizables", cat: "Compute" },
  { en: "App Engine", es: "PaaS sin servidor para apps web/móviles. Standard o Flexible environment", cat: "Compute" },
  { en: "Cloud Run", es: "Containers serverless: despliega un Docker container, paga por request", cat: "Compute" },
  { en: "Cloud Functions", es: "Funciones serverless event-driven (FaaS). Triggered by events", cat: "Compute" },
  { en: "GKE", es: "Google Kubernetes Engine: Kubernetes administrado", cat: "Compute" },
  { en: "Anthos", es: "Plataforma híbrida y multi-cloud para gestionar apps en GKE on-prem y en otras nubes", cat: "Compute" },
  { en: "Sole-tenant nodes", es: "Servidores físicos dedicados (no compartidos) para licencias o compliance", cat: "Compute" },
  // Storage
  { en: "Cloud Storage", es: "Object storage: archivos no estructurados (imágenes, videos, backups)", cat: "Storage" },
  { en: "Storage Class Standard", es: "Acceso frecuente, alta disponibilidad", cat: "Storage" },
  { en: "Storage Class Nearline", es: "Acceso poco frecuente (mensual), 30 días mínimo", cat: "Storage" },
  { en: "Storage Class Coldline", es: "Acceso esporádico (trimestral), 90 días mínimo", cat: "Storage" },
  { en: "Storage Class Archive", es: "Largo plazo, mínimo 365 días. Más barato pero retrieval lento", cat: "Storage" },
  { en: "Persistent Disk", es: "Discos persistentes para VMs (Compute Engine)", cat: "Storage" },
  { en: "Filestore", es: "Sistema de archivos NFS administrado", cat: "Storage" },
  // Databases
  { en: "Cloud SQL", es: "BD relacional administrada: MySQL, PostgreSQL, SQL Server", cat: "Databases" },
  { en: "Cloud Spanner", es: "BD relacional globalmente distribuida, consistencia fuerte, escala horizontal", cat: "Databases" },
  { en: "Firestore", es: "BD NoSQL documental serverless, ideal para apps móviles/web", cat: "Databases" },
  { en: "Bigtable", es: "BD NoSQL wide-column para gran escala (IoT, time series, analytics)", cat: "Databases" },
  { en: "BigQuery", es: "Data warehouse serverless para analytics a petabyte scale", cat: "Databases" },
  { en: "Memorystore", es: "Cache en memoria administrado (Redis o Memcached)", cat: "Databases" },
  { en: "AlloyDB", es: "BD compatible con PostgreSQL optimizada para cargas transaccionales y analytics", cat: "Databases" },
  // Data & Analytics
  { en: "Dataflow", es: "Procesamiento batch y streaming serverless (basado en Apache Beam)", cat: "Data" },
  { en: "Dataproc", es: "Spark y Hadoop administrados", cat: "Data" },
  { en: "Pub/Sub", es: "Mensajería asíncrona escalable globalmente", cat: "Data" },
  { en: "Looker", es: "Plataforma de BI y exploración de datos", cat: "Data" },
  { en: "Looker Studio", es: "Herramienta gratuita de dashboards (antes Data Studio)", cat: "Data" },
  { en: "Data Catalog", es: "Servicio de metadata y descubrimiento de datos", cat: "Data" },
  { en: "Dataplex", es: "Gobierno de datos unificado para data lakes/warehouses/marts", cat: "Data" },
  { en: "Cloud Composer", es: "Apache Airflow administrado para orquestar workflows", cat: "Data" },
  // AI/ML
  { en: "Vertex AI", es: "Plataforma unificada de ML para entrenar, desplegar y gestionar modelos", cat: "AI/ML" },
  { en: "AutoML", es: "Entrenar modelos custom sin código (Vision, NLP, Tabular)", cat: "AI/ML" },
  { en: "Gemini", es: "Familia de modelos LLM multimodales de Google", cat: "AI/ML" },
  { en: "BigQuery ML", es: "Entrenar modelos ML directamente con SQL en BigQuery", cat: "AI/ML" },
  { en: "Vision AI", es: "API pre-entrenada para análisis de imágenes", cat: "AI/ML" },
  { en: "Speech-to-Text", es: "API que convierte audio en texto", cat: "AI/ML" },
  { en: "Text-to-Speech", es: "API que convierte texto en audio natural", cat: "AI/ML" },
  { en: "Translation AI", es: "API de traducción automática", cat: "AI/ML" },
  { en: "Document AI", es: "Extracción de información de documentos", cat: "AI/ML" },
  { en: "Contact Center AI", es: "AI para call centers (Dialogflow + agentes)", cat: "AI/ML" },
  // Networking
  { en: "VPC", es: "Virtual Private Cloud: red privada global", cat: "Networking" },
  { en: "Cloud Load Balancing", es: "Balanceador de carga global o regional", cat: "Networking" },
  { en: "Cloud CDN", es: "Content Delivery Network: cachea contenido cerca de los usuarios", cat: "Networking" },
  { en: "Cloud DNS", es: "DNS administrado de alta disponibilidad", cat: "Networking" },
  { en: "Cloud Interconnect", es: "Conexión dedicada entre on-prem y GCP", cat: "Networking" },
  { en: "Cloud VPN", es: "VPN IPSec sobre internet entre on-prem y GCP", cat: "Networking" },
  { en: "Cloud NAT", es: "NAT administrado para que VMs sin IP pública salgan a internet", cat: "Networking" },
  { en: "Cloud Armor", es: "WAF y protección DDoS para apps en GCP", cat: "Networking" },
  // Security & Identity
  { en: "IAM", es: "Identity and Access Management: quién (identidad) puede hacer qué (rol) sobre cuál recurso", cat: "Security" },
  { en: "Cloud Identity", es: "Identity provider para usuarios y grupos", cat: "Security" },
  { en: "BeyondCorp", es: "Modelo Zero Trust de Google: acceso basado en identidad/dispositivo, no en red", cat: "Security" },
  { en: "Zero Trust", es: "Nunca confíes, siempre verifica. No hay 'red interna confiable'", cat: "Security" },
  { en: "Cloud KMS", es: "Key Management Service: gestiona llaves criptográficas", cat: "Security" },
  { en: "Secret Manager", es: "Almacén de secretos (passwords, API keys)", cat: "Security" },
  { en: "Cloud HSM", es: "Hardware Security Module: llaves en hardware certificado FIPS 140-2 Level 3", cat: "Security" },
  { en: "Security Command Center", es: "Centro unificado de gestión de seguridad y riesgo", cat: "Security" },
  { en: "VPC Service Controls", es: "Perímetros de seguridad para mitigar exfiltración de datos", cat: "Security" },
  { en: "Customer-Managed Encryption Keys (CMEK)", es: "Llaves de encriptación gestionadas por el cliente", cat: "Security" },
  { en: "Customer-Supplied Encryption Keys (CSEK)", es: "Llaves proporcionadas por el cliente para cada operación", cat: "Security" },
  // Operations
  { en: "Cloud Operations Suite", es: "Antes Stackdriver: monitoreo, logging, tracing, profiling", cat: "Operations" },
  { en: "Cloud Logging", es: "Centralizar y analizar logs", cat: "Operations" },
  { en: "Cloud Monitoring", es: "Métricas, dashboards y alertas", cat: "Operations" },
  { en: "Cloud Trace", es: "Distributed tracing para apps", cat: "Operations" },
  { en: "Cloud Profiler", es: "Profiling de CPU/memoria de tus apps", cat: "Operations" },
  { en: "Error Reporting", es: "Agrupa y notifica errores de la app", cat: "Operations" },
  { en: "SRE", es: "Site Reliability Engineering: enfoque de Google para operar sistemas confiables", cat: "Operations" },
  { en: "SLO", es: "Service Level Objective: objetivo interno (ej. 99.9% uptime)", cat: "Operations" },
  { en: "SLA", es: "Service Level Agreement: compromiso contractual con cliente (penalizable)", cat: "Operations" },
  { en: "SLI", es: "Service Level Indicator: lo que mides (latencia, error rate)", cat: "Operations" },
  { en: "Error Budget", es: "100% - SLO. Cuántas fallas te permites", cat: "Operations" },
  // DevOps & Migration
  { en: "Cloud Build", es: "CI/CD administrado", cat: "DevOps" },
  { en: "Artifact Registry", es: "Repositorio de artefactos (containers, paquetes)", cat: "DevOps" },
  { en: "Cloud Source Repositories", es: "Git privado administrado", cat: "DevOps" },
  { en: "Cloud Deploy", es: "Servicio para entregas continuas de apps", cat: "DevOps" },
  { en: "Migrate for Compute Engine", es: "Herramienta para migrar VMs on-prem o de otra nube a GCE", cat: "Migración" },
  { en: "Migrate to Containers", es: "Convierte VMs en containers para GKE", cat: "Migración" },
  { en: "Lift and Shift", es: "Rehost: mover sin cambios (rápido, mínimo beneficio cloud-native)", cat: "Migración" },
  { en: "Improve and Move", es: "Replatform: pequeñas optimizaciones al migrar", cat: "Migración" },
  { en: "Rip and Replace", es: "Refactor/Rebuild: reescribir cloud-native (máximo beneficio)", cat: "Migración" },
  { en: "Database Migration Service", es: "Migración continua de BDs a Cloud SQL/Spanner", cat: "Migración" },
  { en: "Transfer Appliance", es: "Dispositivo físico para mover grandes volúmenes a Cloud Storage", cat: "Migración" },
  { en: "Storage Transfer Service", es: "Transferir datos desde otros clouds o servicios on-line a GCS", cat: "Migración" },
  // Billing & Support
  { en: "Sustained Use Discount (SUD)", es: "Descuento automático por usar VMs continuamente en el mes", cat: "Billing" },
  { en: "Committed Use Discount (CUD)", es: "Descuento por comprometerte a 1 o 3 años de uso", cat: "Billing" },
  { en: "Preemptible VMs", es: "VMs muy baratas que se pueden apagar en 24h (precursor de Spot)", cat: "Billing" },
  { en: "Spot VMs", es: "VMs hasta 91% más baratas, sin tiempo máximo, terminables", cat: "Billing" },
  { en: "Budgets & Alerts", es: "Configurar presupuestos y alertas por gasto en Cloud Billing", cat: "Billing" },
  { en: "Quotas", es: "Límites de recursos por proyecto", cat: "Billing" },
  { en: "Organization Policy", es: "Restricciones a nivel organización (ej. solo regiones permitidas)", cat: "Billing" },
  { en: "Resource Hierarchy", es: "Organization → Folders → Projects → Resources", cat: "Billing" },
  { en: "Support: Basic", es: "Solo documentación y comunidad", cat: "Soporte" },
  { en: "Support: Standard", es: "Soporte business hours, casos no críticos", cat: "Soporte" },
  { en: "Support: Enhanced", es: "Soporte 24/7 con SLA para casos high/medium", cat: "Soporte" },
  { en: "Support: Premium", es: "Soporte 24/7 con TAM (Technical Account Manager)", cat: "Soporte" },
];
