import type { QuizQuestion } from "@/types/course";

export const finalExam: QuizQuestion[] = [
  { q: "¿Cuál es correcto?", options: ["I are a student", "I is a student", "I am a student", "I be a student"], correct: 2 },
  { q: '¿Negativo de "She is at home"?', options: ["She isn't at home", "She not at home", "She doesn't at home", "She no at home"], correct: 0 },
  { q: "¿Pregunta correcta con TO BE?", options: ["You are happy?", "Are you happy?", "Is you happy?", "Do you happy?"], correct: 1 },
  { q: 'Plural de "child":', options: ["childs", "children", "childes", "childrens"], correct: 1 },
  { q: "¿Cuál es correcto?", options: ["a apple", "an apple", "the a apple", "any apple"], correct: 1 },
  { q: 'Posesivo de "they":', options: ["his", "her", "its", "their"], correct: 3 },
  { q: "¿Cuál señala algo cerca y plural?", options: ["this", "that", "these", "those"], correct: 2 },
  { q: 'Presente simple de "she + work":', options: ["She work", "She works", "She working", "She is work"], correct: 1 },
  { q: "¿Pregunta en presente simple?", options: ["You speak English?", "Do you speak English?", "Are you speak English?", "You are speak English?"], correct: 1 },
  { q: "¿Cuál es correcto?", options: ["He doesn't likes", "He doesn't like", "He don't likes", "He not likes"], correct: 1 },
  { q: "¿Cuál es correcto en present continuous?", options: ["I am eat", "I am eating", "I eating", "I eats"], correct: 1 },
  { q: 'Forma -ing de "run":', options: ["runing", "runeing", "running", "runned"], correct: 2 },
  { q: '"¿Estás trabajando?"', options: ["You working?", "Are you working?", "Do you working?", "Is you working?"], correct: 1 },
  { q: '¿Cuál es el pasado de "go"?', options: ["goed", "went", "goes", "gone"], correct: 1 },
  { q: '¿Cuál es el pasado de "buy"?', options: ["buyed", "bought", "buys", "buying"], correct: 1 },
  { q: "¿Cuál es correcto?", options: ["I didn't went", "I didn't go", "I didn't goed", "I no go"], correct: 1 },
  { q: 'Pasado de "to be" para "they":', options: ["was", "were", "is", "are"], correct: 1 },
  { q: "¿Pregunta en pasado?", options: ["Did you went?", "Did you go?", "You go?", "Did go you?"], correct: 1 },
  { q: '"I get up ___ 7 AM"', options: ["at", "in", "on", "to"], correct: 0 },
  { q: '"I was born ___ 1990"', options: ["at", "in", "on", "of"], correct: 1 },
  { q: '"My birthday is ___ Monday"', options: ["at", "in", "on", "to"], correct: 2 },
  { q: '"The book is ___ the table" (sobre)', options: ["in", "under", "on", "at"], correct: 2 },
  { q: "¿Cuál es correcto?", options: ["She can sings", "She can sing", "She cans sing", "She is can sing"], correct: 1 },
  { q: '¿Cómo respondes "Can you swim?" (sí)', options: ["Yes, I am", "Yes, I can", "Yes, I do", "Yes, I swim"], correct: 1 },
  { q: '"___ many people in the room"', options: ["There is", "There are", "There has", "It is"], correct: 1 },
  { q: "¿Cuál es correcto?", options: ["I don't have some money", "I don't have any money", "I don't has any money", "I no have money"], correct: 1 },
  { q: "¿Cómo preguntas el precio?", options: ["How many is?", "How much is it?", "How is it much?", "How money?"], correct: 1 },
  { q: "¿Cuál es correcto?", options: ["I like swim", "I like swimming", "I like to swimming", "I am like swim"], correct: 1 },
  { q: 'Plan futuro con "going to":', options: ["I want to study", "I am going to study", "I study", "I studied"], correct: 1 },
  { q: "Imperativo negativo:", options: ["No talk", "Not talk", "Don't talk", "You don't talk"], correct: 2 },
  { q: '"Hermana" en inglés:', options: ["brother", "sister", "cousin", "aunt"], correct: 1 },
  { q: '"Purple" es:', options: ["rojo", "morado", "naranja", "rosa"], correct: 1 },
  { q: "¿Qué profesión cura?", options: ["teacher", "doctor", "farmer", "lawyer"], correct: 1 },
  { q: '¿Cómo se dice "ojos"?', options: ["eyes", "ears", "feet", "hands"], correct: 0 },
  { q: "¿Qué estación es muy fría?", options: ["summer", "spring", "winter", "autumn"], correct: 2 },
  { q: "¿Qué llevas cuando llueve?", options: ["hat", "sunglasses", "umbrella", "t-shirt"], correct: 2 },
  { q: "¿Cómo vas en autobús?", options: ["by foot", "by bus", "on bus", "in bus"], correct: 1 },
  { q: '¿Cuándo "Good morning"?', options: ["6-12 AM", "12-6 PM", "6 PM-12 AM", "siempre"], correct: 0 },
  { q: "¿Cómo te despides al irte a dormir?", options: ["Good evening", "Good morning", "Good night", "Hello"], correct: 2 },
  { q: "¿Cómo pides un café cortésmente?", options: ["Give me coffee", "Coffee!", "Can I have a coffee, please?", "I want coffee now"], correct: 2 },
  { q: 'Lee: "Tom is 20 years old and he is a student. He likes football and pizza." → ¿Qué edad tiene Tom?', options: ["10", "15", "20", "25"], correct: 2 },
  { q: "Lee el texto anterior → ¿Qué le gusta a Tom?", options: ["Football y pizza", "Tennis y hamburguesas", "Futbol americano", "Baloncesto"], correct: 0 },
  { q: 'Lee: "She doesn\'t live in Madrid. She lives in Barcelona." → ¿Dónde vive ella?', options: ["Madrid", "Barcelona", "París", "Londres"], correct: 1 },
  { q: "¿Cuál es CORRECTO?", options: ["I have 25 years", "I am 25 years old", "I have 25 years old", "I am have 25"], correct: 1 },
  { q: "¿Cuál es CORRECTO?", options: ["I am agree", "I agree", "I am agreeing", "I have agree"], correct: 1 },
  { q: "¿Cuál es CORRECTO?", options: ["She have a car", "She has a car", "She having a car", "She haves a car"], correct: 1 },
  { q: "¿Cuál es CORRECTO?", options: ["I have hungry", "I am hungry", "I has hungry", "I have hunger"], correct: 1 },
  { q: "¿Cuál es CORRECTO?", options: ["The people is happy", "The people are happy", "The peoples are happy", "People is happy"], correct: 1 },
  { q: "¿Cómo preguntas la edad?", options: ["How are you?", "How many years?", "How old are you?", "How much years?"], correct: 2 },
  { q: "¿Cuál es el saludo MÁS formal?", options: ["Hi!", "Hey", "Hello", "What's up"], correct: 2 },
];
