import type { GlossaryEntry } from "@/types/course";

export const glossary: GlossaryEntry[] = [
  // Saludos
  { en: "Hello", es: "Hola", cat: "Saludos" },
  { en: "Hi", es: "Hola (informal)", cat: "Saludos" },
  { en: "Good morning", es: "Buenos días", cat: "Saludos" },
  { en: "Good afternoon", es: "Buenas tardes", cat: "Saludos" },
  { en: "Good evening", es: "Buenas noches (al llegar)", cat: "Saludos" },
  { en: "Good night", es: "Buenas noches (al irse)", cat: "Saludos" },
  { en: "Goodbye", es: "Adiós", cat: "Saludos" },
  { en: "Bye", es: "Chao", cat: "Saludos" },
  { en: "See you later", es: "Hasta luego", cat: "Saludos" },
  // Cortesía
  { en: "Please", es: "Por favor", cat: "Cortesía" },
  { en: "Thank you", es: "Gracias", cat: "Cortesía" },
  { en: "Thanks", es: "Gracias (informal)", cat: "Cortesía" },
  { en: "You're welcome", es: "De nada", cat: "Cortesía" },
  { en: "Excuse me", es: "Disculpe", cat: "Cortesía" },
  { en: "I'm sorry", es: "Lo siento", cat: "Cortesía" },
  // Básico
  { en: "Yes", es: "Sí", cat: "Básico" },
  { en: "No", es: "No", cat: "Básico" },
  // Pronombres
  { en: "I", es: "Yo", cat: "Pronombres" },
  { en: "You", es: "Tú/Ustedes", cat: "Pronombres" },
  { en: "He", es: "Él", cat: "Pronombres" },
  { en: "She", es: "Ella", cat: "Pronombres" },
  { en: "It", es: "Eso (cosa)", cat: "Pronombres" },
  { en: "We", es: "Nosotros", cat: "Pronombres" },
  { en: "They", es: "Ellos/Ellas", cat: "Pronombres" },
  // Familia
  { en: "family", es: "familia", cat: "Familia" },
  { en: "father / dad", es: "padre / papá", cat: "Familia" },
  { en: "mother / mom", es: "madre / mamá", cat: "Familia" },
  { en: "son", es: "hijo", cat: "Familia" },
  { en: "daughter", es: "hija", cat: "Familia" },
  { en: "brother", es: "hermano", cat: "Familia" },
  { en: "sister", es: "hermana", cat: "Familia" },
  { en: "grandfather", es: "abuelo", cat: "Familia" },
  { en: "grandmother", es: "abuela", cat: "Familia" },
  { en: "uncle", es: "tío", cat: "Familia" },
  { en: "aunt", es: "tía", cat: "Familia" },
  { en: "cousin", es: "primo/a", cat: "Familia" },
  { en: "husband", es: "esposo", cat: "Familia" },
  { en: "wife", es: "esposa", cat: "Familia" },
  { en: "children", es: "niños/hijos", cat: "Familia" },
  { en: "baby", es: "bebé", cat: "Familia" },
  // Colores
  { en: "red", es: "rojo", cat: "Colores" },
  { en: "blue", es: "azul", cat: "Colores" },
  { en: "green", es: "verde", cat: "Colores" },
  { en: "yellow", es: "amarillo", cat: "Colores" },
  { en: "black", es: "negro", cat: "Colores" },
  { en: "white", es: "blanco", cat: "Colores" },
  { en: "orange", es: "naranja", cat: "Colores" },
  { en: "pink", es: "rosa", cat: "Colores" },
  { en: "purple", es: "morado", cat: "Colores" },
  { en: "brown", es: "marrón", cat: "Colores" },
  { en: "gray", es: "gris", cat: "Colores" },
  // Comida
  { en: "food", es: "comida", cat: "Comida" },
  { en: "water", es: "agua", cat: "Comida" },
  { en: "milk", es: "leche", cat: "Comida" },
  { en: "bread", es: "pan", cat: "Comida" },
  { en: "coffee", es: "café", cat: "Comida" },
  { en: "tea", es: "té", cat: "Comida" },
  { en: "chicken", es: "pollo", cat: "Comida" },
  { en: "fish", es: "pescado", cat: "Comida" },
  { en: "meat", es: "carne", cat: "Comida" },
  { en: "rice", es: "arroz", cat: "Comida" },
  { en: "cheese", es: "queso", cat: "Comida" },
  { en: "egg", es: "huevo", cat: "Comida" },
  { en: "fruit", es: "fruta", cat: "Comida" },
  { en: "apple", es: "manzana", cat: "Comida" },
  { en: "banana", es: "plátano", cat: "Comida" },
  { en: "vegetables", es: "verduras", cat: "Comida" },
  { en: "salad", es: "ensalada", cat: "Comida" },
  { en: "soup", es: "sopa", cat: "Comida" },
  { en: "sugar", es: "azúcar", cat: "Comida" },
  { en: "salt", es: "sal", cat: "Comida" },
  { en: "breakfast", es: "desayuno", cat: "Comida" },
  { en: "lunch", es: "almuerzo", cat: "Comida" },
  { en: "dinner", es: "cena", cat: "Comida" },
  // Días
  { en: "Monday", es: "Lunes", cat: "Días" },
  { en: "Tuesday", es: "Martes", cat: "Días" },
  { en: "Wednesday", es: "Miércoles", cat: "Días" },
  { en: "Thursday", es: "Jueves", cat: "Días" },
  { en: "Friday", es: "Viernes", cat: "Días" },
  { en: "Saturday", es: "Sábado", cat: "Días" },
  { en: "Sunday", es: "Domingo", cat: "Días" },
  // Tiempo
  { en: "today", es: "hoy", cat: "Tiempo" },
  { en: "tomorrow", es: "mañana", cat: "Tiempo" },
  { en: "yesterday", es: "ayer", cat: "Tiempo" },
  { en: "week", es: "semana", cat: "Tiempo" },
  { en: "month", es: "mes", cat: "Tiempo" },
  { en: "year", es: "año", cat: "Tiempo" },
  { en: "last night", es: "anoche", cat: "Tiempo" },
  { en: "last week", es: "la semana pasada", cat: "Tiempo" },
  { en: "two days ago", es: "hace dos días", cat: "Tiempo" },
  { en: "next week", es: "la próxima semana", cat: "Tiempo" },
  { en: "tonight", es: "esta noche", cat: "Tiempo" },
  { en: "soon", es: "pronto", cat: "Tiempo" },
  // Casa
  { en: "house", es: "casa", cat: "Casa" },
  { en: "home", es: "hogar", cat: "Casa" },
  { en: "room", es: "habitación", cat: "Casa" },
  { en: "bedroom", es: "dormitorio", cat: "Casa" },
  { en: "kitchen", es: "cocina", cat: "Casa" },
  { en: "bathroom", es: "baño", cat: "Casa" },
  { en: "living room", es: "sala", cat: "Casa" },
  { en: "door", es: "puerta", cat: "Casa" },
  { en: "window", es: "ventana", cat: "Casa" },
  { en: "table", es: "mesa", cat: "Casa" },
  { en: "chair", es: "silla", cat: "Casa" },
  { en: "bed", es: "cama", cat: "Casa" },
  { en: "TV", es: "televisión", cat: "Casa" },
  // Ropa
  { en: "shirt", es: "camisa", cat: "Ropa" },
  { en: "T-shirt", es: "camiseta", cat: "Ropa" },
  { en: "pants", es: "pantalones", cat: "Ropa" },
  { en: "jeans", es: "vaqueros", cat: "Ropa" },
  { en: "shorts", es: "pantalón corto", cat: "Ropa" },
  { en: "skirt", es: "falda", cat: "Ropa" },
  { en: "dress", es: "vestido", cat: "Ropa" },
  { en: "shoes", es: "zapatos", cat: "Ropa" },
  { en: "boots", es: "botas", cat: "Ropa" },
  { en: "jacket", es: "chaqueta", cat: "Ropa" },
  { en: "coat", es: "abrigo", cat: "Ropa" },
  { en: "sweater", es: "suéter", cat: "Ropa" },
  { en: "hat", es: "sombrero", cat: "Ropa" },
  { en: "cap", es: "gorra", cat: "Ropa" },
  { en: "socks", es: "calcetines", cat: "Ropa" },
  { en: "scarf", es: "bufanda", cat: "Ropa" },
  { en: "gloves", es: "guantes", cat: "Ropa" },
  { en: "belt", es: "cinturón", cat: "Ropa" },
  { en: "tie", es: "corbata", cat: "Ropa" },
  { en: "glasses", es: "gafas", cat: "Ropa" },
  // Cuerpo
  { en: "head", es: "cabeza", cat: "Cuerpo" },
  { en: "face", es: "cara", cat: "Cuerpo" },
  { en: "eye", es: "ojo", cat: "Cuerpo" },
  { en: "ear", es: "oreja", cat: "Cuerpo" },
  { en: "nose", es: "nariz", cat: "Cuerpo" },
  { en: "mouth", es: "boca", cat: "Cuerpo" },
  { en: "hand", es: "mano", cat: "Cuerpo" },
  { en: "arm", es: "brazo", cat: "Cuerpo" },
  { en: "leg", es: "pierna", cat: "Cuerpo" },
  { en: "foot / feet", es: "pie / pies", cat: "Cuerpo" },
  { en: "hair", es: "pelo", cat: "Cuerpo" },
  { en: "shoulder", es: "hombro", cat: "Cuerpo" },
  { en: "elbow", es: "codo", cat: "Cuerpo" },
  { en: "knee", es: "rodilla", cat: "Cuerpo" },
  { en: "finger", es: "dedo", cat: "Cuerpo" },
  { en: "toe", es: "dedo del pie", cat: "Cuerpo" },
  { en: "chest", es: "pecho", cat: "Cuerpo" },
  { en: "neck", es: "cuello", cat: "Cuerpo" },
  { en: "tooth / teeth", es: "diente / dientes", cat: "Cuerpo" },
  { en: "tongue", es: "lengua", cat: "Cuerpo" },
  { en: "stomach", es: "estómago", cat: "Cuerpo" },
  // Verbos
  { en: "to be", es: "ser/estar", cat: "Verbos" },
  { en: "to have", es: "tener", cat: "Verbos" },
  { en: "to do", es: "hacer", cat: "Verbos" },
  { en: "to go", es: "ir", cat: "Verbos" },
  { en: "to come", es: "venir", cat: "Verbos" },
  { en: "to eat", es: "comer", cat: "Verbos" },
  { en: "to drink", es: "beber", cat: "Verbos" },
  { en: "to sleep", es: "dormir", cat: "Verbos" },
  { en: "to work", es: "trabajar", cat: "Verbos" },
  { en: "to study", es: "estudiar", cat: "Verbos" },
  { en: "to live", es: "vivir", cat: "Verbos" },
  { en: "to like", es: "gustar", cat: "Verbos" },
  { en: "to want", es: "querer", cat: "Verbos" },
  { en: "to need", es: "necesitar", cat: "Verbos" },
  { en: "to speak", es: "hablar", cat: "Verbos" },
  { en: "to read", es: "leer", cat: "Verbos" },
  { en: "to write", es: "escribir", cat: "Verbos" },
  { en: "to listen", es: "escuchar", cat: "Verbos" },
  { en: "to watch", es: "ver/mirar", cat: "Verbos" },
  { en: "to play", es: "jugar/tocar", cat: "Verbos" },
  { en: "to swim", es: "nadar", cat: "Verbos" },
  { en: "to dance", es: "bailar", cat: "Verbos" },
  // Verbos irregulares (pasado)
  { en: "go → went", es: "ir → fue", cat: "Verbos irregulares" },
  { en: "have → had", es: "tener → tuvo", cat: "Verbos irregulares" },
  { en: "do → did", es: "hacer → hizo", cat: "Verbos irregulares" },
  { en: "be → was/were", es: "ser → fue/era", cat: "Verbos irregulares" },
  { en: "see → saw", es: "ver → vio", cat: "Verbos irregulares" },
  { en: "eat → ate", es: "comer → comió", cat: "Verbos irregulares" },
  { en: "drink → drank", es: "beber → bebió", cat: "Verbos irregulares" },
  { en: "sleep → slept", es: "dormir → durmió", cat: "Verbos irregulares" },
  { en: "say → said", es: "decir → dijo", cat: "Verbos irregulares" },
  { en: "tell → told", es: "contar → contó", cat: "Verbos irregulares" },
  { en: "give → gave", es: "dar → dio", cat: "Verbos irregulares" },
  { en: "take → took", es: "tomar → tomó", cat: "Verbos irregulares" },
  { en: "come → came", es: "venir → vino", cat: "Verbos irregulares" },
  { en: "make → made", es: "hacer → hizo", cat: "Verbos irregulares" },
  { en: "get → got", es: "obtener → obtuvo", cat: "Verbos irregulares" },
  { en: "buy → bought", es: "comprar → compró", cat: "Verbos irregulares" },
  { en: "find → found", es: "encontrar → encontró", cat: "Verbos irregulares" },
  { en: "write → wrote", es: "escribir → escribió", cat: "Verbos irregulares" },
  { en: "read → read", es: "leer → leyó (suena red)", cat: "Verbos irregulares" },
  { en: "know → knew", es: "saber → supo", cat: "Verbos irregulares" },
  { en: "think → thought", es: "pensar → pensó", cat: "Verbos irregulares" },
  { en: "speak → spoke", es: "hablar → habló", cat: "Verbos irregulares" },
  { en: "hear → heard", es: "oír → oyó", cat: "Verbos irregulares" },
  { en: "run → ran", es: "correr → corrió", cat: "Verbos irregulares" },
  { en: "swim → swam", es: "nadar → nadó", cat: "Verbos irregulares" },
  { en: "sing → sang", es: "cantar → cantó", cat: "Verbos irregulares" },
  { en: "feel → felt", es: "sentir → sintió", cat: "Verbos irregulares" },
  { en: "leave → left", es: "irse → se fue", cat: "Verbos irregulares" },
  { en: "begin → began", es: "empezar → empezó", cat: "Verbos irregulares" },
  { en: "can → could", es: "poder → pudo", cat: "Verbos irregulares" },
  // Lugares
  { en: "school", es: "escuela", cat: "Lugares" },
  { en: "university", es: "universidad", cat: "Lugares" },
  { en: "office", es: "oficina", cat: "Lugares" },
  { en: "hospital", es: "hospital", cat: "Lugares" },
  { en: "bank", es: "banco", cat: "Lugares" },
  { en: "park", es: "parque", cat: "Lugares" },
  { en: "restaurant", es: "restaurante", cat: "Lugares" },
  { en: "supermarket", es: "supermercado", cat: "Lugares" },
  { en: "street", es: "calle", cat: "Lugares" },
  { en: "city", es: "ciudad", cat: "Lugares" },
  { en: "country", es: "país", cat: "Lugares" },
  { en: "beach", es: "playa", cat: "Lugares" },
  { en: "church", es: "iglesia", cat: "Lugares" },
  { en: "hotel", es: "hotel", cat: "Lugares" },
  // Adjetivos
  { en: "big", es: "grande", cat: "Adjetivos" },
  { en: "small", es: "pequeño", cat: "Adjetivos" },
  { en: "tall", es: "alto", cat: "Adjetivos" },
  { en: "short", es: "corto/bajo", cat: "Adjetivos" },
  { en: "long", es: "largo", cat: "Adjetivos" },
  { en: "old", es: "viejo", cat: "Adjetivos" },
  { en: "new", es: "nuevo", cat: "Adjetivos" },
  { en: "young", es: "joven", cat: "Adjetivos" },
  { en: "good", es: "bueno", cat: "Adjetivos" },
  { en: "bad", es: "malo", cat: "Adjetivos" },
  { en: "happy", es: "feliz", cat: "Adjetivos" },
  { en: "sad", es: "triste", cat: "Adjetivos" },
  { en: "easy", es: "fácil", cat: "Adjetivos" },
  { en: "difficult", es: "difícil", cat: "Adjetivos" },
  { en: "hot", es: "caliente", cat: "Adjetivos" },
  { en: "cold", es: "frío", cat: "Adjetivos" },
  { en: "beautiful", es: "hermoso", cat: "Adjetivos" },
  { en: "fast", es: "rápido", cat: "Adjetivos" },
  { en: "slow", es: "lento", cat: "Adjetivos" },
  // Preposiciones
  { en: "in", es: "en/dentro", cat: "Preposiciones" },
  { en: "on", es: "sobre/encima", cat: "Preposiciones" },
  { en: "at", es: "en (lugar/hora)", cat: "Preposiciones" },
  { en: "under", es: "debajo", cat: "Preposiciones" },
  { en: "over", es: "sobre", cat: "Preposiciones" },
  { en: "next to", es: "al lado de", cat: "Preposiciones" },
  { en: "behind", es: "detrás", cat: "Preposiciones" },
  { en: "in front of", es: "delante de", cat: "Preposiciones" },
  { en: "between", es: "entre", cat: "Preposiciones" },
  { en: "with", es: "con", cat: "Preposiciones" },
  { en: "without", es: "sin", cat: "Preposiciones" },
  { en: "for", es: "para/por", cat: "Preposiciones" },
  // Conectores
  { en: "and", es: "y", cat: "Conectores" },
  { en: "or", es: "o", cat: "Conectores" },
  { en: "but", es: "pero", cat: "Conectores" },
  { en: "because", es: "porque", cat: "Conectores" },
  { en: "so", es: "tan/así que", cat: "Conectores" },
  { en: "also", es: "también", cat: "Conectores" },
  // Preguntas
  { en: "what", es: "qué", cat: "Preguntas" },
  { en: "who", es: "quién", cat: "Preguntas" },
  { en: "where", es: "dónde", cat: "Preguntas" },
  { en: "when", es: "cuándo", cat: "Preguntas" },
  { en: "why", es: "por qué", cat: "Preguntas" },
  { en: "how", es: "cómo", cat: "Preguntas" },
  { en: "how many", es: "cuántos", cat: "Preguntas" },
  { en: "how much", es: "cuánto", cat: "Preguntas" },
  // Números
  { en: "one", es: "uno", cat: "Números" },
  { en: "two", es: "dos", cat: "Números" },
  { en: "three", es: "tres", cat: "Números" },
  { en: "ten", es: "diez", cat: "Números" },
  { en: "twenty", es: "veinte", cat: "Números" },
  { en: "hundred", es: "cien", cat: "Números" },
  { en: "thousand", es: "mil", cat: "Números" },
  // Animales
  { en: "dog", es: "perro", cat: "Animales" },
  { en: "cat", es: "gato", cat: "Animales" },
  { en: "bird", es: "pájaro", cat: "Animales" },
  { en: "horse", es: "caballo", cat: "Animales" },
  { en: "cow", es: "vaca", cat: "Animales" },
  { en: "pig", es: "cerdo", cat: "Animales" },
  // Profesiones
  { en: "teacher", es: "profesor", cat: "Profesiones" },
  { en: "doctor", es: "doctor", cat: "Profesiones" },
  { en: "nurse", es: "enfermera", cat: "Profesiones" },
  { en: "student", es: "estudiante", cat: "Profesiones" },
  { en: "engineer", es: "ingeniero", cat: "Profesiones" },
  { en: "lawyer", es: "abogado", cat: "Profesiones" },
  { en: "cook / chef", es: "cocinero", cat: "Profesiones" },
  { en: "driver", es: "conductor", cat: "Profesiones" },
  { en: "police officer", es: "policía", cat: "Profesiones" },
  { en: "waiter", es: "mesero", cat: "Profesiones" },
  { en: "firefighter", es: "bombero", cat: "Profesiones" },
  { en: "farmer", es: "granjero", cat: "Profesiones" },
  { en: "manager", es: "gerente", cat: "Profesiones" },
  { en: "designer", es: "diseñador", cat: "Profesiones" },
  { en: "artist", es: "artista", cat: "Profesiones" },
  { en: "writer", es: "escritor", cat: "Profesiones" },
  // Transporte
  { en: "car", es: "coche", cat: "Transporte" },
  { en: "plane", es: "avión", cat: "Transporte" },
  { en: "train", es: "tren", cat: "Transporte" },
  { en: "bus", es: "autobús", cat: "Transporte" },
  { en: "taxi", es: "taxi", cat: "Transporte" },
  { en: "bike / bicycle", es: "bicicleta", cat: "Transporte" },
  { en: "motorcycle", es: "moto", cat: "Transporte" },
  { en: "truck", es: "camión", cat: "Transporte" },
  { en: "subway / metro", es: "metro", cat: "Transporte" },
  { en: "boat / ship", es: "barco", cat: "Transporte" },
  { en: "on foot", es: "a pie", cat: "Transporte" },
  // Sentimientos
  { en: "angry", es: "enfadado", cat: "Sentimientos" },
  { en: "scared", es: "asustado", cat: "Sentimientos" },
  { en: "tired", es: "cansado", cat: "Sentimientos" },
  { en: "excited", es: "emocionado", cat: "Sentimientos" },
  { en: "nervous", es: "nervioso", cat: "Sentimientos" },
  { en: "bored", es: "aburrido", cat: "Sentimientos" },
  { en: "surprised", es: "sorprendido", cat: "Sentimientos" },
  { en: "hungry", es: "hambriento", cat: "Sentimientos" },
  { en: "thirsty", es: "sediento", cat: "Sentimientos" },
  { en: "sick / ill", es: "enfermo", cat: "Sentimientos" },
  // Deportes
  { en: "football / soccer", es: "fútbol", cat: "Deportes" },
  { en: "basketball", es: "baloncesto", cat: "Deportes" },
  { en: "tennis", es: "tenis", cat: "Deportes" },
  { en: "swimming", es: "natación", cat: "Deportes" },
  { en: "running", es: "correr", cat: "Deportes" },
  { en: "yoga", es: "yoga", cat: "Deportes" },
  { en: "gym", es: "gimnasio", cat: "Deportes" },
  // Tiempo (clima)
  { en: "sunny", es: "soleado", cat: "Clima" },
  { en: "cloudy", es: "nublado", cat: "Clima" },
  { en: "rainy", es: "lluvioso", cat: "Clima" },
  { en: "windy", es: "ventoso", cat: "Clima" },
  { en: "snowy", es: "nevado", cat: "Clima" },
  { en: "spring", es: "primavera", cat: "Clima" },
  { en: "summer", es: "verano", cat: "Clima" },
  { en: "autumn / fall", es: "otoño", cat: "Clima" },
  { en: "winter", es: "invierno", cat: "Clima" },
  // Cuantificadores
  { en: "some", es: "algo/algunos", cat: "Cuantificadores" },
  { en: "any", es: "algo/cualquier", cat: "Cuantificadores" },
  { en: "many", es: "muchos", cat: "Cuantificadores" },
  { en: "much", es: "mucho", cat: "Cuantificadores" },
  { en: "a lot of", es: "mucho/muchos", cat: "Cuantificadores" },
  { en: "a few", es: "unos pocos", cat: "Cuantificadores" },
  { en: "a little", es: "un poco", cat: "Cuantificadores" },
  { en: "no / none", es: "ninguno", cat: "Cuantificadores" },
  // Frecuencia
  { en: "always", es: "siempre", cat: "Frecuencia" },
  { en: "usually", es: "usualmente", cat: "Frecuencia" },
  { en: "often", es: "a menudo", cat: "Frecuencia" },
  { en: "sometimes", es: "a veces", cat: "Frecuencia" },
  { en: "rarely", es: "raramente", cat: "Frecuencia" },
  { en: "never", es: "nunca", cat: "Frecuencia" },
  // Compras
  { en: "money", es: "dinero", cat: "Compras" },
  { en: "cash", es: "efectivo", cat: "Compras" },
  { en: "credit card", es: "tarjeta de crédito", cat: "Compras" },
  { en: "price", es: "precio", cat: "Compras" },
  { en: "cheap", es: "barato", cat: "Compras" },
  { en: "expensive", es: "caro", cat: "Compras" },
  { en: "free", es: "gratis", cat: "Compras" },
  { en: "shop / store", es: "tienda", cat: "Compras" },
  { en: "buy", es: "comprar", cat: "Compras" },
  { en: "sell", es: "vender", cat: "Compras" },
  { en: "pay", es: "pagar", cat: "Compras" },
];
