import type { GlossaryEntry } from "@/types/course";

export const glossary: GlossaryEntry[] = [
  // Fundamentos
  { en: "AWS", es: "Amazon Web Services: plataforma cloud de Amazon, líder global", cat: "Fundamentos" },
  { en: "Cloud Computing", es: "Entrega de recursos IT bajo demanda vía internet con pago por uso", cat: "Fundamentos" },
  { en: "IaaS", es: "Infrastructure as a Service: VMs, red, storage (ej. EC2)", cat: "Fundamentos" },
  { en: "PaaS", es: "Platform as a Service: plataforma con runtime gestionado (ej. Elastic Beanstalk)", cat: "Fundamentos" },
  { en: "SaaS", es: "Software as a Service: software listo (ej. WorkMail, WorkDocs)", cat: "Fundamentos" },
  { en: "On-premise", es: "Infraestructura propia en datacenter de la empresa", cat: "Fundamentos" },
  { en: "Hybrid Cloud", es: "Mezcla de on-prem y cloud público (AWS Outposts, Storage Gateway)", cat: "Fundamentos" },
  { en: "Multi-Cloud", es: "Uso de varios proveedores cloud simultáneamente", cat: "Fundamentos" },
  { en: "CapEx", es: "Capital Expenditure: inversión en activos. Cloud lo reduce", cat: "Fundamentos" },
  { en: "OpEx", es: "Operational Expenditure: gasto operativo recurrente. Lo que cobra cloud", cat: "Fundamentos" },
  { en: "TCO", es: "Total Cost of Ownership: costo total a lo largo del ciclo de vida", cat: "Fundamentos" },

  // Infraestructura Global
  { en: "Region", es: "Área geográfica con múltiples AZs (ej. us-east-1, eu-west-1)", cat: "Global Infrastructure" },
  { en: "Availability Zone (AZ)", es: "Datacenter independiente dentro de una región (mínimo 3 por región)", cat: "Global Infrastructure" },
  { en: "Edge Location", es: "Punto de presencia (PoP) global para caché y baja latencia", cat: "Global Infrastructure" },
  { en: "Regional Edge Cache", es: "Cache intermedio entre origen y edge", cat: "Global Infrastructure" },
  { en: "Local Zone", es: "Extensión de región más cerca de usuarios (baja latencia ultra-localizada)", cat: "Global Infrastructure" },
  { en: "Wavelength Zone", es: "Servicios AWS en redes 5G de operadoras (ultra baja latencia móvil)", cat: "Global Infrastructure" },
  { en: "AWS Outposts", es: "Hardware AWS instalado en tu datacenter (cloud híbrido)", cat: "Global Infrastructure" },

  // Compute
  { en: "EC2 (Elastic Compute Cloud)", es: "VMs IaaS de AWS, núcleo del cómputo", cat: "Compute" },
  { en: "AMI (Amazon Machine Image)", es: "Plantilla para crear instancias EC2 (OS + software)", cat: "Compute" },
  { en: "Instance Type", es: "Familia y tamaño de EC2 (ej. t3.micro, m5.large, c5.xlarge)", cat: "Compute" },
  { en: "EBS (Elastic Block Store)", es: "Discos persistentes para EC2", cat: "Compute" },
  { en: "Instance Store", es: "Storage físico de la instancia EC2, EFÍMERO", cat: "Compute" },
  { en: "Auto Scaling Group (ASG)", es: "Grupo de EC2 que escala automáticamente según demanda", cat: "Compute" },
  { en: "Elastic Load Balancing (ELB)", es: "Balanceador de carga (ALB, NLB, GLB, CLB)", cat: "Compute" },
  { en: "Lambda", es: "Funciones serverless (FaaS) event-driven", cat: "Compute" },
  { en: "ECS (Elastic Container Service)", es: "Orquestador propio de AWS para containers", cat: "Compute" },
  { en: "EKS (Elastic Kubernetes Service)", es: "Kubernetes administrado por AWS", cat: "Compute" },
  { en: "Fargate", es: "Serverless para containers ECS/EKS (sin gestionar instancias)", cat: "Compute" },
  { en: "Lightsail", es: "VPS simplificado de AWS (precio fijo mensual)", cat: "Compute" },
  { en: "Elastic Beanstalk", es: "PaaS de AWS para deploys de apps sin gestionar infra", cat: "Compute" },
  { en: "Batch", es: "Procesamiento batch a escala (jobs paralelos)", cat: "Compute" },

  // Storage
  { en: "S3 (Simple Storage Service)", es: "Object storage, durabilidad 11 nueves", cat: "Storage" },
  { en: "S3 Standard", es: "Clase para acceso frecuente, alta disponibilidad", cat: "Storage" },
  { en: "S3 Intelligent-Tiering", es: "Mueve objetos automáticamente entre clases según acceso", cat: "Storage" },
  { en: "S3 Standard-IA", es: "Acceso infrecuente, más barato pero con costo de retrieval", cat: "Storage" },
  { en: "S3 One Zone-IA", es: "Como Standard-IA pero en UNA sola AZ (menos disponibilidad)", cat: "Storage" },
  { en: "S3 Glacier Instant Retrieval", es: "Archivado con acceso en milisegundos", cat: "Storage" },
  { en: "S3 Glacier Flexible Retrieval", es: "Archivado con retrieval en minutos-horas", cat: "Storage" },
  { en: "S3 Glacier Deep Archive", es: "Archivado más barato, retrieval en 12 horas", cat: "Storage" },
  { en: "S3 Lifecycle Policies", es: "Reglas para mover/borrar objetos automáticamente", cat: "Storage" },
  { en: "S3 Versioning", es: "Mantener múltiples versiones de un objeto", cat: "Storage" },
  { en: "S3 Cross-Region Replication", es: "Replicar bucket a otra región automáticamente", cat: "Storage" },
  { en: "EFS (Elastic File System)", es: "NFS administrado, escalable, compartido entre EC2", cat: "Storage" },
  { en: "FSx", es: "Filesystems gestionados (Windows, Lustre, NetApp ONTAP, OpenZFS)", cat: "Storage" },
  { en: "Storage Gateway", es: "Conexión híbrida storage on-prem ↔ AWS", cat: "Storage" },
  { en: "Snow Family", es: "Dispositivos físicos para mover grandes volúmenes (Snowcone, Snowball, Snowmobile)", cat: "Storage" },
  { en: "Backup", es: "Servicio centralizado de backups (RDS, EBS, EFS, DynamoDB, etc.)", cat: "Storage" },

  // Databases
  { en: "RDS (Relational Database Service)", es: "BD relacional administrada (MySQL, PostgreSQL, MariaDB, Oracle, SQL Server)", cat: "Databases" },
  { en: "Aurora", es: "BD relacional de AWS compatible con MySQL/PostgreSQL, 5x más rápida", cat: "Databases" },
  { en: "Aurora Serverless", es: "Aurora que escala automáticamente, paga por uso", cat: "Databases" },
  { en: "DynamoDB", es: "NoSQL key-value/documental serverless con latencia <10ms", cat: "Databases" },
  { en: "DynamoDB Accelerator (DAX)", es: "Cache in-memory para DynamoDB (microsegundos)", cat: "Databases" },
  { en: "ElastiCache", es: "Cache in-memory administrado (Redis o Memcached)", cat: "Databases" },
  { en: "Redshift", es: "Data warehouse para analytics a escala petabyte", cat: "Databases" },
  { en: "Neptune", es: "BD de grafos administrada", cat: "Databases" },
  { en: "DocumentDB", es: "BD compatible con MongoDB", cat: "Databases" },
  { en: "Keyspaces", es: "Compatible con Apache Cassandra", cat: "Databases" },
  { en: "Timestream", es: "BD para time-series", cat: "Databases" },
  { en: "QLDB (Quantum Ledger DB)", es: "BD inmutable y auditable (blockchain-like)", cat: "Databases" },
  { en: "Database Migration Service (DMS)", es: "Migrar BDs a AWS con mínimo downtime", cat: "Databases" },

  // Networking
  { en: "VPC (Virtual Private Cloud)", es: "Red privada virtual aislada en AWS (regional)", cat: "Networking" },
  { en: "Subnet", es: "Rango de IPs dentro de VPC, asignado a UNA AZ", cat: "Networking" },
  { en: "Internet Gateway (IGW)", es: "Salida a internet desde la VPC", cat: "Networking" },
  { en: "NAT Gateway", es: "Permite a subnets privadas salir a internet (sin entrar)", cat: "Networking" },
  { en: "Security Group", es: "Firewall a nivel instancia (stateful)", cat: "Networking" },
  { en: "Network ACL (NACL)", es: "Firewall a nivel subnet (stateless)", cat: "Networking" },
  { en: "Route Table", es: "Tabla de rutas en la VPC", cat: "Networking" },
  { en: "VPC Peering", es: "Conectar dos VPCs entre sí (no transitivo)", cat: "Networking" },
  { en: "Transit Gateway", es: "Hub central para conectar múltiples VPCs y on-prem", cat: "Networking" },
  { en: "VPN (Virtual Private Network)", es: "Conexión IPsec sobre internet entre on-prem y AWS", cat: "Networking" },
  { en: "Direct Connect", es: "Conexión física dedicada con AWS (alto bandwidth, baja latencia)", cat: "Networking" },
  { en: "Route 53", es: "DNS administrado de AWS, alta disponibilidad, routing policies", cat: "Networking" },
  { en: "CloudFront", es: "CDN global de AWS, integra con +600 PoPs", cat: "Networking" },
  { en: "Global Accelerator", es: "Mejora latencia/disponibilidad usando red AWS Anycast", cat: "Networking" },
  { en: "ELB (Elastic Load Balancing)", es: "Balanceadores: ALB (L7), NLB (L4), GLB (L3)", cat: "Networking" },
  { en: "API Gateway", es: "Crear, publicar y gestionar APIs REST/HTTP/WebSocket", cat: "Networking" },

  // Security & Identity
  { en: "IAM (Identity and Access Management)", es: "Gestión de identidades y permisos en AWS", cat: "Security" },
  { en: "IAM User", es: "Identidad de usuario humano o aplicación", cat: "Security" },
  { en: "IAM Group", es: "Conjunto de usuarios para asignar permisos colectivamente", cat: "Security" },
  { en: "IAM Role", es: "Identidad para servicios/temporal con permisos", cat: "Security" },
  { en: "IAM Policy", es: "JSON que define permisos (Allow/Deny actions sobre resources)", cat: "Security" },
  { en: "MFA (Multi-Factor Authentication)", es: "Segundo factor (app, SMS, hardware) además de password", cat: "Security" },
  { en: "AWS Organizations", es: "Gestión central de múltiples cuentas AWS", cat: "Security" },
  { en: "Service Control Policy (SCP)", es: "Política que limita máximos permisos en una cuenta/OU", cat: "Security" },
  { en: "AWS SSO / IAM Identity Center", es: "Single Sign-On para AWS y SaaS", cat: "Security" },
  { en: "Cognito", es: "Identity provider para apps (signup/login, OAuth)", cat: "Security" },
  { en: "KMS (Key Management Service)", es: "Gestión de llaves criptográficas", cat: "Security" },
  { en: "CloudHSM", es: "Hardware Security Module dedicado (FIPS 140-2 Level 3)", cat: "Security" },
  { en: "Secrets Manager", es: "Almacenar y rotar secretos (passwords, API keys)", cat: "Security" },
  { en: "Systems Manager Parameter Store", es: "Almacén jerárquico de parámetros (alternativa más barata)", cat: "Security" },
  { en: "Certificate Manager (ACM)", es: "Provisionar y gestionar certificados SSL/TLS gratis", cat: "Security" },
  { en: "Shield Standard", es: "Protección DDoS automática y gratuita", cat: "Security" },
  { en: "Shield Advanced", es: "Protección DDoS avanzada con SLA y soporte (paga)", cat: "Security" },
  { en: "WAF (Web Application Firewall)", es: "Filtra tráfico HTTP malicioso (SQL injection, XSS)", cat: "Security" },
  { en: "GuardDuty", es: "Threat detection con ML (analiza logs, DNS, VPC Flow)", cat: "Security" },
  { en: "Inspector", es: "Análisis automatizado de vulnerabilidades en EC2 y containers", cat: "Security" },
  { en: "Macie", es: "Detecta datos sensibles (PII) en S3 con ML", cat: "Security" },
  { en: "Security Hub", es: "Centro unificado de hallazgos de seguridad", cat: "Security" },
  { en: "Detective", es: "Análisis e investigación de incidentes de seguridad", cat: "Security" },
  { en: "Artifact", es: "Portal de reportes de compliance (SOC, ISO, PCI)", cat: "Security" },
  { en: "Audit Manager", es: "Audita continuamente compliance" , cat: "Security" },
  { en: "Network Firewall", es: "Firewall administrado para VPC", cat: "Security" },

  // Management & Monitoring
  { en: "CloudWatch", es: "Monitoreo: métricas, logs, alarmas, dashboards", cat: "Management" },
  { en: "CloudWatch Logs", es: "Centralizar y analizar logs" , cat: "Management" },
  { en: "CloudWatch Alarms", es: "Alertas basadas en umbrales de métricas", cat: "Management" },
  { en: "CloudTrail", es: "Registro de TODAS las llamadas API de AWS (auditoría)", cat: "Management" },
  { en: "Config", es: "Inventario y configuración de recursos, compliance", cat: "Management" },
  { en: "Trusted Advisor", es: "Recomendaciones: costo, seguridad, fault tolerance, performance, service limits", cat: "Management" },
  { en: "Systems Manager", es: "Gestión operativa centralizada (patch, run command, sessions)", cat: "Management" },
  { en: "CloudFormation", es: "IaC declarativa nativa de AWS (JSON/YAML)", cat: "Management" },
  { en: "CDK (Cloud Development Kit)", es: "IaC con lenguajes de programación (TypeScript, Python, etc.)", cat: "Management" },
  { en: "OpsWorks", es: "Chef y Puppet administrados", cat: "Management" },
  { en: "Control Tower", es: "Setup automatizado de landing zones multi-cuenta", cat: "Management" },
  { en: "AWS Health Dashboard", es: "Estado de servicios AWS y eventos que te afectan", cat: "Management" },
  { en: "Personal Health Dashboard", es: "Eventos específicos que impactan TU cuenta", cat: "Management" },

  // Application Integration
  { en: "SNS (Simple Notification Service)", es: "Pub/sub messaging (notificaciones)", cat: "Integration" },
  { en: "SQS (Simple Queue Service)", es: "Cola de mensajes para desacoplar componentes", cat: "Integration" },
  { en: "EventBridge", es: "Event bus serverless con reglas", cat: "Integration" },
  { en: "Step Functions", es: "Orquestar workflows con state machines visuales", cat: "Integration" },
  { en: "MQ", es: "Message broker compatible con ActiveMQ y RabbitMQ", cat: "Integration" },

  // Analytics
  { en: "Athena", es: "Queries SQL serverless sobre datos en S3", cat: "Analytics" },
  { en: "QuickSight", es: "BI y dashboards de AWS", cat: "Analytics" },
  { en: "Kinesis", es: "Familia para streaming: Data Streams, Firehose, Analytics, Video Streams", cat: "Analytics" },
  { en: "Glue", es: "ETL serverless con catálogo de datos", cat: "Analytics" },
  { en: "EMR", es: "Hadoop/Spark/Hive administrado", cat: "Analytics" },
  { en: "Lake Formation", es: "Construir y gestionar data lakes", cat: "Analytics" },

  // AI/ML
  { en: "SageMaker", es: "Plataforma ML end-to-end de AWS", cat: "AI/ML" },
  { en: "Bedrock", es: "Acceso a foundation models (Claude, Llama, Titan) vía API", cat: "AI/ML" },
  { en: "Rekognition", es: "Análisis de imágenes y videos (API pre-entrenada)", cat: "AI/ML" },
  { en: "Comprehend", es: "NLP (entidades, sentiment, idioma) vía API", cat: "AI/ML" },
  { en: "Polly", es: "Text-to-Speech con voces naturales", cat: "AI/ML" },
  { en: "Transcribe", es: "Speech-to-Text", cat: "AI/ML" },
  { en: "Translate", es: "Traducción automática", cat: "AI/ML" },
  { en: "Lex", es: "Chatbots conversacionales (mismo motor que Alexa)", cat: "AI/ML" },
  { en: "Textract", es: "Extraer texto, formularios, tablas de documentos", cat: "AI/ML" },
  { en: "Personalize", es: "Recomendaciones personalizadas", cat: "AI/ML" },

  // Migration
  { en: "AWS Migration Hub", es: "Tracking centralizado de migraciones", cat: "Migration" },
  { en: "Application Migration Service (MGN)", es: "Lift-and-shift de servidores a AWS", cat: "Migration" },
  { en: "Application Discovery Service", es: "Descubrir servidores on-prem para planificar migración", cat: "Migration" },
  { en: "DataSync", es: "Transferir datos on-prem ↔ AWS automatizado", cat: "Migration" },
  { en: "Schema Conversion Tool (SCT)", es: "Convertir esquemas de BD (Oracle → PostgreSQL)", cat: "Migration" },

  // Pricing & Billing & Support
  { en: "Free Tier", es: "Tres tipos: 12 meses gratis, always free, free trials", cat: "Pricing" },
  { en: "On-Demand", es: "Pago por uso sin compromiso (más caro)", cat: "Pricing" },
  { en: "Reserved Instance (RI)", es: "Compromiso 1 o 3 años, hasta 72% off", cat: "Pricing" },
  { en: "Savings Plan", es: "Compromiso de uso $/hora (más flexible que RIs)", cat: "Pricing" },
  { en: "Spot Instance", es: "Hasta 90% off, terminables con 2 min de aviso", cat: "Pricing" },
  { en: "Dedicated Host", es: "Servidor físico dedicado (licencias)", cat: "Pricing" },
  { en: "Dedicated Instance", es: "Instancia en hardware dedicado", cat: "Pricing" },
  { en: "AWS Pricing Calculator", es: "Estimar costos antes de desplegar", cat: "Pricing" },
  { en: "Cost Explorer", es: "Visualizar y analizar costos pasados y proyectados", cat: "Pricing" },
  { en: "AWS Budgets", es: "Establecer presupuestos con alertas", cat: "Pricing" },
  { en: "Cost and Usage Report (CUR)", es: "Reporte detallado exportable a S3", cat: "Pricing" },
  { en: "Compute Optimizer", es: "Recomendaciones de right-sizing", cat: "Pricing" },
  { en: "Support: Basic", es: "Gratis: docs, foros, health dashboard", cat: "Soporte" },
  { en: "Support: Developer", es: "Business hours, casos no críticos. ~$29/mes", cat: "Soporte" },
  { en: "Support: Business", es: "24/7, 1h respuesta P1, todos los servicios", cat: "Soporte" },
  { en: "Support: Enterprise On-Ramp", es: "24/7 + acceso parcial a TAM, 30min P1", cat: "Soporte" },
  { en: "Support: Enterprise", es: "24/7, TAM dedicado, 15min P1, IEM (Infrastructure Event Management)", cat: "Soporte" },
  { en: "Concierge Team", es: "Equipo de billing/account dedicado (Enterprise)", cat: "Soporte" },

  // Frameworks
  { en: "Well-Architected Framework", es: "6 pilares: Operational, Security, Reliability, Performance, Cost, Sustainability", cat: "Frameworks" },
  { en: "Cloud Adoption Framework (CAF)", es: "6 perspectivas: Business, People, Governance, Platform, Security, Operations", cat: "Frameworks" },
  { en: "Shared Responsibility Model", es: "AWS asegura del cloud; cliente asegura en el cloud", cat: "Frameworks" },

  // Otros
  { en: "AWS Marketplace", es: "Catálogo de software de terceros para usar en AWS", cat: "Otros" },
  { en: "AWS Partner Network (APN)", es: "Red de partners certificados", cat: "Otros" },
  { en: "AWS re:Invent", es: "Conferencia anual de AWS donde lanzan productos", cat: "Otros" },
];
