import type { QuizQuestion } from "@/types/course";

export const finalExam: QuizQuestion[] = [
  { q: "¿Qué significa DDD?", options: ["Database Driven Development", "Domain-Driven Design", "Data Distribution Design", "Distributed Data Design"], correct: 1 },
  { q: "¿Qué es el Core Domain?", options: ["Cualquier funcionalidad", "Lo que diferencia tu negocio del resto", "Una librería externa", "La base de datos"], correct: 1 },
  { q: "¿Qué es Ubiquitous Language?", options: ["Programar en varios idiomas", "Vocabulario común entre devs y negocio", "Internacionalización", "Un framework"], correct: 1 },
  { q: "¿Qué es un Bounded Context?", options: ["Una clase", "Frontera donde un modelo es consistente y único", "Un microservicio cualquiera", "Una base de datos"], correct: 1 },
  { q: "Diferencia entre Entity y Value Object:", options: ["Son lo mismo", "Entity tiene identidad, Value Object no", "Value Object es persistente, Entity no", "Entity es mutable, Value Object inmutable y sin identidad"], correct: 3 },
  { q: "¿Qué garantiza la consistencia en un Aggregate?", options: ["La base de datos", "El Aggregate Root", "El repositorio", "El servicio de aplicación"], correct: 1 },
  { q: "¿Para qué sirve un Repository?", options: ["Renderizar UI", "Abstraer la persistencia de agregados", "Procesar eventos", "Validar formularios"], correct: 1 },
  { q: "¿Qué es un Domain Event?", options: ["Una excepción", "Algo importante que pasó en el dominio", "Un click del usuario", "Una promesa"], correct: 1 },
  { q: "¿Qué patrón separa lecturas de escrituras?", options: ["MVC", "CQRS", "Singleton", "Observer"], correct: 1 },
  { q: "¿Qué es Event Sourcing?", options: ["Renderizar eventos UI", "Persistir el estado como secuencia de eventos", "Logging", "Pub/Sub"], correct: 1 },
  { q: "Hexagonal Architecture también se llama:", options: ["MVC", "Ports & Adapters", "Onion", "Layered"], correct: 1 },
  { q: "¿Qué hace una Anti-Corruption Layer?", options: ["Limpia código sucio", "Traduce entre dos bounded contexts distintos", "Encripta datos", "Valida formularios"], correct: 1 },
  { q: "¿Qué es una invariante?", options: ["Una constante", "Regla que SIEMPRE debe cumplirse", "Una variable global", "Un valor que cambia"], correct: 1 },
  { q: "Un Application Service debe contener:", options: ["Lógica de negocio compleja", "Orquestación de casos de uso sin lógica de dominio", "Solo SQL", "Vistas HTML"], correct: 1 },
  { q: "¿Qué es un Use Case?", options: ["Una clase abstracta", "Una intención del usuario (Crear Pedido, etc.)", "Una vista", "Un test"], correct: 1 },
  { q: "Un Command representa:", options: ["Una lectura", "Una intención de cambiar el estado", "Una respuesta", "Un evento"], correct: 1 },
  { q: "¿Qué es eventual consistency?", options: ["Inconsistencia eterna", "Los datos convergen al estado correcto eventualmente", "Datos siempre sincronizados", "Sin consistencia"], correct: 1 },
  { q: "El Outbox Pattern garantiza:", options: ["Storage barato", "Entrega confiable de eventos junto con cambios de datos", "Cache invalidation", "Encriptación"], correct: 1 },
  { q: "¿Qué es un Saga?", options: ["Una historia", "Transacción larga entre servicios con compensaciones", "Un test", "Una vista"], correct: 1 },
  { q: "El principio de Dependency Inversion dice:", options: ["Las clases dependen de implementaciones", "Las capas internas no dependen de las externas", "Hay que invertir el orden de imports", "No usar interfaces"], correct: 1 },
  { q: "Un Subdominio Genérico es:", options: ["Lo más importante", "Resuelto por soluciones existentes (auth, email)", "Único de tu negocio", "Algo opcional"], correct: 1 },
  { q: "¿Qué define una Entity?", options: ["Sus atributos", "Su identidad única que persiste en el tiempo", "Su tamaño", "Su tipo"], correct: 1 },
  { q: "Un Value Object es:", options: ["Mutable", "Inmutable, sin identidad, definido por sus atributos", "Persistente con ID", "Una entidad pequeña"], correct: 1 },
  { q: "Un Aggregate puede tener:", options: ["Cualquier tamaño sin reglas", "Múltiples entidades y VOs con una raíz como entrada", "Solo VOs", "Solo entidades"], correct: 1 },
  { q: "¿Qué relación tienen dos Bounded Contexts en Context Map?", options: ["Siempre Shared Kernel", "Pueden ser: Partnership, Customer/Supplier, ACL, etc.", "Solo se ignoran", "Siempre comparten BD"], correct: 1 },
  { q: "¿Cuál es la regla de oro para escribir tests en DDD?", options: ["Solo tests E2E", "Tests del dominio independientes de frameworks/DB", "No tests", "Solo tests manuales"], correct: 1 },
  { q: "¿Qué NO debería tener un agregado?", options: ["Invariantes", "Identidad", "Referencias por ID a otros agregados", "Referencias directas a objetos de otros agregados"], correct: 3 },
  { q: "Un Domain Service se usa cuando:", options: ["Hay UI", "La lógica no pertenece a una entidad sola", "Hay BD", "Hay JSON"], correct: 1 },
  { q: "¿Qué representa un Port en arquitectura hexagonal?", options: ["Un puerto TCP", "Una interfaz que la app expone o consume", "Un endpoint HTTP", "Un Docker port"], correct: 1 },
  { q: "Un Adapter:", options: ["Es una interfaz", "Es la implementación concreta de un Port", "Es un test", "Es una entidad"], correct: 1 },
];
