import type { QuizQuestion } from "@/types/course";

export const finalExam: QuizQuestion[] = [
  { q: "¿Qué representa DevOps?", options: ["Una herramienta", "Una cultura que une desarrollo y operaciones", "Un framework", "Un IDE"], correct: 1 },
  { q: "¿Qué significa CI/CD?", options: ["Code Init / Code Deploy", "Continuous Integration / Continuous Delivery", "Container Install / Cluster Deploy", "Cloud Install / Cloud Deploy"], correct: 1 },
  { q: "¿Qué comando inicializa un repositorio Git?", options: ["git start", "git init", "git create", "git new"], correct: 1 },
  { q: "¿Qué comando muestra el estado del repositorio?", options: ["git show", "git state", "git status", "git info"], correct: 2 },
  { q: "¿Qué archivo define cómo se construye una imagen Docker?", options: ["Dockerfile", "docker.yml", "image.config", "container.json"], correct: 0 },
  { q: "¿Qué comando lista los contenedores en ejecución?", options: ["docker list", "docker ps", "docker show", "docker running"], correct: 1 },
  { q: "¿Cuál es la unidad mínima ejecutable en Kubernetes?", options: ["Container", "Pod", "Service", "Deployment"], correct: 1 },
  { q: "¿Qué recurso de Kubernetes gestiona réplicas de pods?", options: ["Service", "Ingress", "Deployment", "Namespace"], correct: 2 },
  { q: "¿Qué herramienta es IaC declarativa multi-cloud?", options: ["Ansible", "Terraform", "Jenkins", "Helm"], correct: 1 },
  { q: "¿Qué herramienta usa playbooks en YAML para gestión de configuración?", options: ["Terraform", "Ansible", "Pulumi", "Vagrant"], correct: 1 },
  { q: "¿Qué es un 'pipeline'?", options: ["Una tubería de agua", "Secuencia automatizada de build/test/deploy", "Un archivo de log", "Un tipo de container"], correct: 1 },
  { q: "¿Qué plataforma de CI/CD está integrada en GitHub?", options: ["GitLab CI", "Jenkins", "GitHub Actions", "CircleCI"], correct: 2 },
  { q: "¿Qué estrategia de deploy usa dos entornos paralelos?", options: ["Canary", "Blue/Green", "Rolling", "Recreate"], correct: 1 },
  { q: "¿Qué hace 'kubectl apply -f file.yaml'?", options: ["Aplica recursos definidos en el archivo", "Borra el archivo", "Edita el archivo", "Visualiza el archivo"], correct: 0 },
  { q: "¿Qué herramienta monitorea métricas?", options: ["Grafana", "Prometheus", "ELK", "Kibana"], correct: 1 },
  { q: "¿Para qué se usa Grafana?", options: ["Almacenar logs", "Recolectar métricas", "Visualizar dashboards", "Hacer deploys"], correct: 2 },
  { q: "¿Qué significa SLO?", options: ["Service Level Objective", "Software Layer Output", "Secure Login Operation", "System Lock Override"], correct: 0 },
  { q: "¿Qué principio dice 'dar el mínimo permiso necesario'?", options: ["RBAC", "Least Privilege", "Zero Trust", "Defense in Depth"], correct: 1 },
  { q: "¿Qué es un 'secret' en Kubernetes?", options: ["Una contraseña en texto plano", "Información sensible encriptada", "Un archivo de logs", "Un endpoint"], correct: 1 },
  { q: "¿Qué comando crea una rama en Git?", options: ["git create branch", "git branch nombre", "git new branch", "git fork"], correct: 1 },
  { q: "¿Qué comando cambia de rama?", options: ["git switch nombre / git checkout nombre", "git change", "git move", "git select"], correct: 0 },
  { q: "¿Cuál es la diferencia entre `git merge` y `git rebase`?", options: ["Son lo mismo", "Merge crea commit de fusión, rebase reescribe historial", "Rebase es más rápido siempre", "Merge solo funciona en main"], correct: 1 },
  { q: "¿Qué archivo describe los servicios en docker-compose?", options: ["docker.json", "compose.yml / docker-compose.yml", "services.txt", "Dockerfile"], correct: 1 },
  { q: "¿Qué hace `docker build -t myapp .`?", options: ["Lanza un contenedor", "Construye una imagen llamada myapp", "Sube la imagen", "Lista imágenes"], correct: 1 },
  { q: "¿Qué es un Pod en Kubernetes?", options: ["Un servidor físico", "Una unidad con 1 o más contenedores", "Un namespace", "Un volumen"], correct: 1 },
  { q: "¿Qué hace un Ingress?", options: ["Almacena datos", "Enruta tráfico HTTP externo a servicios", "Encripta secretos", "Reinicia pods"], correct: 1 },
  { q: "¿Qué herramienta gestiona paquetes en Kubernetes?", options: ["pip", "npm", "Helm", "apt"], correct: 2 },
  { q: "¿Qué hace 'terraform plan'?", options: ["Aplica cambios", "Muestra qué cambios se aplicarían", "Borra recursos", "Crea un nuevo proyecto"], correct: 1 },
  { q: "¿Qué hace 'terraform apply'?", options: ["Aplica los cambios planificados", "Solo muestra cambios", "Inicializa providers", "Valida sintaxis"], correct: 0 },
  { q: "¿Qué es DevSecOps?", options: ["Solo DevOps en empresas grandes", "Integrar seguridad en el ciclo DevOps", "Una nueva nube", "Un certificado"], correct: 1 },
  { q: "¿Qué representa SAST?", options: ["Static Application Security Testing", "Server Activity Status Test", "Secure App Storage Token", "System Audit Stack Tool"], correct: 0 },
  { q: "¿Qué hace cron?", options: ["Programa tareas periódicas en Linux", "Conecta servidores", "Comprime archivos", "Gestiona usuarios"], correct: 0 },
  { q: "¿Qué comando muestra procesos en ejecución?", options: ["ls", "ps", "cat", "grep"], correct: 1 },
  { q: "¿Qué comando se usa para SSH?", options: ["ssh usuario@host", "ssh-connect host", "connect ssh host", "remote host"], correct: 0 },
  { q: "¿Qué es VPC?", options: ["Virtual Private Cloud", "Virtual Personal Computer", "Verified Public Channel", "Virtualized Provider Container"], correct: 0 },
  { q: "¿Qué hace un load balancer?", options: ["Comprime imágenes", "Reparte tráfico entre instancias", "Almacena logs", "Encripta datos"], correct: 1 },
  { q: "¿Qué es auto-scaling?", options: ["Escalado manual", "Ajustar capacidad automáticamente según demanda", "Reiniciar servidores", "Comprimir disco"], correct: 1 },
  { q: "¿Qué es GitOps?", options: ["Una nube nueva", "Usar Git como única fuente de verdad para infra y deploys", "Un fork de Git", "Una herramienta de monitoreo"], correct: 1 },
  { q: "¿Qué hace un 'tag' en Git?", options: ["Marca un commit como versión/release", "Borra commits", "Crea una rama", "Fusiona ramas"], correct: 0 },
  { q: "¿Qué comando despliega un Helm chart?", options: ["helm deploy", "helm install nombre chart", "helm apply", "helm run"], correct: 1 },
];
