import type { GlossaryEntry } from "@/types/course";

export const glossary: GlossaryEntry[] = [
  // Conceptos básicos
  { en: "DevOps", es: "Cultura que combina desarrollo (Dev) y operaciones (Ops)", cat: "Fundamentos" },
  { en: "CI", es: "Integración Continua: integrar cambios al repositorio frecuentemente", cat: "Fundamentos" },
  { en: "CD", es: "Continuous Delivery / Deployment: entrega o despliegue continuo automatizado", cat: "Fundamentos" },
  { en: "SRE", es: "Site Reliability Engineering: ingeniería de fiabilidad de sitios", cat: "Fundamentos" },
  { en: "IaC", es: "Infrastructure as Code: infraestructura definida como código", cat: "Fundamentos" },
  { en: "GitOps", es: "Gestionar infraestructura y deployments desde Git como única fuente de verdad", cat: "Fundamentos" },
  // Git
  { en: "git", es: "Sistema de control de versiones distribuido", cat: "Git" },
  { en: "repository", es: "Repositorio: contenedor de código con historial completo", cat: "Git" },
  { en: "commit", es: "Captura de cambios en el historial del repositorio", cat: "Git" },
  { en: "branch", es: "Rama: línea independiente de desarrollo", cat: "Git" },
  { en: "merge", es: "Fusionar cambios de una rama en otra", cat: "Git" },
  { en: "rebase", es: "Reaplicar commits sobre otra base (reescribe historial)", cat: "Git" },
  { en: "pull request (PR)", es: "Solicitud de revisión y merge de cambios", cat: "Git" },
  { en: "fork", es: "Copia de un repositorio bajo tu cuenta", cat: "Git" },
  { en: "tag", es: "Marca un commit como release/versión", cat: "Git" },
  { en: "stash", es: "Guardar cambios sin commit para volver luego", cat: "Git" },
  // Docker
  { en: "Docker", es: "Plataforma de contenedores", cat: "Docker" },
  { en: "container", es: "Instancia ejecutable de una imagen, aislada del host", cat: "Docker" },
  { en: "image", es: "Plantilla inmutable con app + dependencias", cat: "Docker" },
  { en: "Dockerfile", es: "Receta para construir una imagen", cat: "Docker" },
  { en: "docker-compose", es: "Orquestar múltiples contenedores con un YAML", cat: "Docker" },
  { en: "registry", es: "Repositorio de imágenes (Docker Hub, ECR, GHCR)", cat: "Docker" },
  { en: "volume", es: "Almacenamiento persistente para contenedores", cat: "Docker" },
  { en: "bind mount", es: "Montar una ruta del host en el contenedor", cat: "Docker" },
  // Kubernetes
  { en: "Kubernetes (k8s)", es: "Orquestador de contenedores", cat: "Kubernetes" },
  { en: "pod", es: "Unidad mínima ejecutable: uno o varios contenedores", cat: "Kubernetes" },
  { en: "deployment", es: "Recurso que gestiona réplicas de pods", cat: "Kubernetes" },
  { en: "service", es: "Exposición estable de un grupo de pods", cat: "Kubernetes" },
  { en: "ingress", es: "Regla de enrutamiento HTTP externo a servicios", cat: "Kubernetes" },
  { en: "namespace", es: "Espacio lógico para separar recursos", cat: "Kubernetes" },
  { en: "ConfigMap", es: "Configuración no sensible como clave/valor", cat: "Kubernetes" },
  { en: "Secret", es: "Información sensible encriptada (passwords, keys)", cat: "Kubernetes" },
  { en: "kubectl", es: "CLI para interactuar con Kubernetes", cat: "Kubernetes" },
  { en: "Helm", es: "Gestor de paquetes para Kubernetes (charts)", cat: "Kubernetes" },
  // CI/CD
  { en: "pipeline", es: "Secuencia automatizada de pasos (build, test, deploy)", cat: "CI/CD" },
  { en: "GitHub Actions", es: "Plataforma de CI/CD integrada en GitHub", cat: "CI/CD" },
  { en: "GitLab CI", es: "Plataforma de CI/CD de GitLab", cat: "CI/CD" },
  { en: "Jenkins", es: "Servidor de automatización open source veterano", cat: "CI/CD" },
  { en: "artifact", es: "Salida construida por un pipeline (binario, imagen, paquete)", cat: "CI/CD" },
  { en: "runner", es: "Máquina que ejecuta jobs del pipeline", cat: "CI/CD" },
  { en: "trigger", es: "Evento que dispara el pipeline (push, PR, schedule)", cat: "CI/CD" },
  { en: "rollback", es: "Volver a una versión anterior si falla el deploy", cat: "CI/CD" },
  { en: "blue/green", es: "Estrategia de deploy con dos entornos paralelos", cat: "CI/CD" },
  { en: "canary", es: "Deploy gradual a un % de usuarios para validar", cat: "CI/CD" },
  // Linux / Shell
  { en: "shell", es: "Intérprete de comandos (bash, zsh, fish)", cat: "Linux" },
  { en: "cron", es: "Programador de tareas en Linux", cat: "Linux" },
  { en: "systemd", es: "Sistema de init y gestión de servicios", cat: "Linux" },
  { en: "ssh", es: "Conexión remota segura a otro servidor", cat: "Linux" },
  { en: "permissions (chmod)", es: "Control de lectura/escritura/ejecución", cat: "Linux" },
  { en: "process (ps)", es: "Programa en ejecución", cat: "Linux" },
  { en: "logs", es: "Registros de eventos generados por una app o sistema", cat: "Linux" },
  // IaC / Terraform / Cloud
  { en: "Terraform", es: "Herramienta IaC declarativa multi-cloud (HCL)", cat: "IaC" },
  { en: "Ansible", es: "Gestión de configuración con playbooks (YAML)", cat: "IaC" },
  { en: "Pulumi", es: "IaC usando lenguajes de programación reales", cat: "IaC" },
  { en: "module (Terraform)", es: "Paquete reutilizable de configuración", cat: "IaC" },
  { en: "state", es: "Archivo que mapea recursos reales con tu config", cat: "IaC" },
  { en: "provider (Terraform)", es: "Plugin que habla con una nube/servicio", cat: "IaC" },
  { en: "VPC", es: "Red privada virtual en la nube", cat: "Cloud" },
  { en: "EC2", es: "Servidor virtual en AWS", cat: "Cloud" },
  { en: "S3", es: "Almacenamiento de objetos en AWS", cat: "Cloud" },
  { en: "load balancer", es: "Reparte tráfico entre varias instancias", cat: "Cloud" },
  { en: "auto-scaling", es: "Ajustar capacidad automáticamente según demanda", cat: "Cloud" },
  // Observabilidad
  { en: "Prometheus", es: "Sistema de monitoreo de métricas", cat: "Observabilidad" },
  { en: "Grafana", es: "Dashboards y visualización de métricas", cat: "Observabilidad" },
  { en: "ELK stack", es: "Elasticsearch + Logstash + Kibana para logs", cat: "Observabilidad" },
  { en: "tracing", es: "Seguimiento de una request a través de servicios", cat: "Observabilidad" },
  { en: "metric", es: "Valor numérico medido en el tiempo", cat: "Observabilidad" },
  { en: "alert", es: "Notificación cuando una métrica sale del rango", cat: "Observabilidad" },
  { en: "SLO", es: "Service Level Objective: objetivo de fiabilidad", cat: "Observabilidad" },
  { en: "SLA", es: "Service Level Agreement: compromiso contractual", cat: "Observabilidad" },
  { en: "SLI", es: "Service Level Indicator: indicador medido", cat: "Observabilidad" },
  // Seguridad
  { en: "secrets management", es: "Gestión segura de credenciales (Vault, Secrets Manager)", cat: "Seguridad" },
  { en: "RBAC", es: "Role-Based Access Control: control de acceso por roles", cat: "Seguridad" },
  { en: "least privilege", es: "Principio de mínimo privilegio necesario", cat: "Seguridad" },
  { en: "scan / vulnerability scan", es: "Detectar vulnerabilidades en código o imágenes", cat: "Seguridad" },
  { en: "SAST", es: "Static Application Security Testing", cat: "Seguridad" },
  { en: "DAST", es: "Dynamic Application Security Testing", cat: "Seguridad" },
  { en: "DevSecOps", es: "Integrar seguridad en el ciclo DevOps", cat: "Seguridad" },
];
